### ISSUE TITLE
Please license this

### ISSUE THREAD

**Issue by 4PwP** [YellowCat98/Serpent#3]
under what license is this? you should add a LICENSE.md file so people
A: don't steal any of your code
B: are free of doing specific actions decided by you.

My personal recommendations would be AGPL (GNU Affero General Public License) it lets the user freedom of use, but also provides anti-theft measures from the owner side.

```
-----BEGIN PUBLIC KEY-----
MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgGW3aqk3Rz+VF1HT+Gddin2osq/9
4yDYtzqoY3/VmRrFxP4bCNETth8VcxAY0x5Pf10Lj5yYT4KqikF4z2TNFnoNNbZt
NoH2txNFTxOsL0DVdSdzdH0QBG3X6sZmOY8UuK+W+ohJ7TsuPNdd5Sje/t6HG55o
DyKieowAmtb0wTyRAgMBAAE=
-----END PUBLIC KEY-----```

**Comment by YellowCat98** [comment]
i forgot to license it, thanks tho
